name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update image
      run: sudo apt -y update
    - name: Install tauri dependencies
      run: sudo apt -y install libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
    - name: Install cargo-audit
      run: cargo install cargo-audit
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Test
      working-directory: ./src-tauri
      run: cargo test --verbose
    - name: Audit
      working-directory: ./src-tauri
      run: cargo audit
    - name: Check formatting
      working-directory: ./src-tauri
      run: cargo fmt --all -- --check
